
[tool.black]
line-length = 120
target-version = ["py311"]
extended-exclude = '''
env
'''

[tool.autoflake]
check = true
in-place = true
remove-unused-variables = true
remove-duplicates-keys = true
remove-all-unused-imports = true
